### ISSUE TITLE
pytest.mark.parametrize  put chinese into  ids list display garbled code

### ISSUE THREAD

**Issue by dengyouxinviabtc** [kondratyev-nv/vscode-python-test-adapter#214] opened 2020-12-04 10:20 UTC
run test show that:
ERROR: not found: e:\api_autotest\testcase\test_account.py::test_create_observer[æ­£å¸¸æ·»å è§å¯è]

**Comment by kondratyev-nv** [comment] 2020-12-05 18:30
@dengyouxinviabtc Thank you for the issue! Unfortunately, I can't reproduce the it. I used the following test
```
import pytest

@pytest.mark.parametrize("test_input", ["漢字"])
def test_eval(test_input):
    assert test_input is not None
```

In test explorer panel I can see 
![image](https://user-images.githubusercontent.com/4085884/101260405-8e903600-3727-11eb-9aae-d8dd2ce8f0cf.png)
that test is passed, even through the name looks incorrect.

Can you please provide more details or a small reproduceable example? A screenshot can also help.

**Comment by dengyouxinviabtc** [comment] 2020-12-07 05:23
Thank you for&nbsp;answer！
I create a new project,it is normal,and i can run them.



but in my old project ,i can run it ,maybe&nbsp;my env have some problem.


i got this error when i run the test&nbsp; in my old&nbsp; project.






&nbsp;
than，i check my env ，and&nbsp; found the&nbsp;reason is that i write some code in conftest.py&nbsp; as follows:



&nbsp;
finally, This problem has been solved。
i delete that code and&nbsp; config "disable_test_id_escaping_and_forfeit_all_rights_to_community_support=True" in file pytest.ini make chinese effect


Thanks.






------------------&nbsp;Original&nbsp;------------------

**Comment by kondratyev-nv** [comment] 2020-12-07 13:47
As I understood you, the issue is resolved now, so I'm closing it. In case I missed something, feel free to reopen it and add any additional details 🙂

**Closed by kondratyev-nv** 2020-12-07 13:47 UTC
