### ISSUE TITLE
Occur "ImportError while loading conftest ..." after gevent monkey patching

### ISSUE THREAD

**Issue by mcauto** [kondratyev-nv/vscode-python-test-adapter#119] opened 2020-01-21 00:33 UTC
![image](https://user-images.githubusercontent.com/15080806/72765565-588db480-3c30-11ea-9c5f-487829d4077f.png)

If you click 'Debug Test` or `Debug`, the following error occurs.

```bash
ImportError while loading conftest '${PATH}/conftest.py'.
RuntimeError: cannot release un-acquired lock
```

I want to use breakpoints.

## code 

```python
from gevent import monkey
monkey.patch_all()
from app.test.mock import token
from app.test.mock.api import response
```

**Comment by kondratyev-nv** [comment] 2020-01-21 16:50
@mcauto Thank you for the issue! It looks like something is wrong with your configuration. This extension uses debug configuration from the Python extension. So if the `Debug Test` is not working, I would suggest you report the issue to the Python extension - https://github.com/microsoft/vscode-python. 

I can point out that the `'${PATH}/conftest.py'` looks suspicious. At least because the `PATH` environment variable is usually is a _set_ of directories. Also, do you mind providing a small example to reproduce the issue?

**Comment by mcauto** [comment] 2020-01-22 04:42
@kondratyev-nv 

sample project here! https://github.com/mcauto/vscode-python-test-gevent-bug/pull/1

**Comment by kondratyev-nv** [comment] 2020-01-23 13:25
@mcauto Thank you for the sample project. I can reproduce the issue. However, as I expected, the Python extension has the same issue. I've reported it in https://github.com/microsoft/vscode-python/issues/9735. If there is any additional information, please, add it there.

**Comment by kondratyev-nv** [comment] 2020-01-24 12:50
@mcauto It looks like it is https://github.com/microsoft/ptvsd/ issue. You can try insiders build of the Python Extension, see https://github.com/microsoft/ptvsd/issues/1706#issuecomment-572287267 for details. Also, to successfully debug your sample code I have to change .env file to
```
PIPENV_VENV_IN_PROJECT=${PWD}
PYTHONPATH=${PWD}/app
DEBUG=True
GEVENT_SUPPORT=True
```
With these changes debug successfully stops on a breakpoint
![image](https://user-images.githubusercontent.com/4085884/73070330-1af38a80-3ec1-11ea-9947-b87c684f040b.png)

**Comment by mcauto** [comment] 2020-01-28 01:19
@kondratyev-nv 

https://github.com/microsoft/ptvsd/issues/1706#issuecomment-579033907

I'm using wsl2. 

I don't use `--install-extension` options in code cli. 😢

**Comment by kondratyev-nv** [comment] 2020-01-28 06:30
@mcauto If your question is about how to install insider's build, then you don't have to use CLI for this. It can be done from the VS Code interface.
![image](https://user-images.githubusercontent.com/4085884/73240499-28a25c00-41b0-11ea-8c0e-449fe961e5ef.png)
Choose Install from VSIX and then choose a downloaded .vsix file. 

Unfortunately, if you don't want to bother with all these, you have to wait for the next stable release of the Python extension, see https://github.com/microsoft/ptvsd/issues/2054#issuecomment-579005796.

**Comment by mcauto** [comment] 2020-01-28 07:26
@kondratyev-nv 

Thank you! 

but, I have to wait for the next stable release.. OTL

![image](https://user-images.githubusercontent.com/15080806/73243339-a420ff00-41ea-11ea-9b4f-b74259a59aef.png)

**Comment by kondratyev-nv** [comment] 2020-01-28 13:43
This is unfortunate indeed :( I will close this issue since it looks like no modifications are required to the extension. However, if anything would not work after the fixes from ptvsd and the Python extension, feel free to report an issue!

**Closed by kondratyev-nv** 2020-01-28 13:43 UTC
