### ISSUE TITLE
Tests complete but keep spinning

### ISSUE THREAD

**Issue by v-kydela** [kondratyev-nv/vscode-python-test-adapter#108] opened 2019-10-24 18:33 UTC
When I run tests in the test UI, I can see in the Python Test Log that the tests have completed but the icons keep spinning and never change to a completed icon:

![image](https://user-images.githubusercontent.com/41968495/67514455-9a1ebb80-f651-11e9-8fc3-7cf93a0820b0.png)

After running the tests, if I try to run other tests then they won't even change to a spinning icon to begin with, but the tests still run. The icons just don't change.

**Comment by kondratyev-nv** [comment] 2019-10-24 18:53
@v-kydela Thank you for the issue! The screenshot shows the tests from the [Python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python). If the issue is about their icons, please, report this issue to them.

Tests from this extension [Python Test Explorer for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=LittleFoxTeam.vscode-python-test-adapter) are located under the "Test Explorer" section.
![image](https://user-images.githubusercontent.com/4085884/67516001-7a66b200-f6a8-11e9-9385-4fc9be05ed4b.png)
If you have the extension from this repository installed and there are any issues with that, please, consult the output Python Test Adapter Log in the Output section.

**Comment by kondratyev-nv** [comment] 2019-10-24 19:00
@v-kydela I belive this is related to https://github.com/microsoft/vscode-python/issues/7618.

**Comment by kondratyev-nv** [comment] 2019-10-29 18:27
@v-kydela I'm closing this issue. If you have any issues with Python Test Explorer for Visual Studio Code, feel free to comment or open a new one.

**Closed by kondratyev-nv** 2019-10-29 18:27 UTC
