### ISSUE TITLE
.env variables are not loaded before executing test for Django

### ISSUE THREAD

**Issue by mawan5512** [kondratyev-nv/vscode-python-test-adapter#80] opened 2019-05-09 17:19 UTC
I have prepared my Django project and most of the settings are set using environment variables. Since I've made this change the Test Explorer shows test discovery as failed because it cannot find the DJANGO_SETTINGS_MODULE environment variable in the list of available environment variables. 

I have given the python.envfile path for the extension to look for environment variables from the postactivate file as shown below.

> {

    "python.pythonPath": "/Users/<user_name>/.virtualenvs/<folder_name>/bin/python",
    "python.envFile": "/Users/<user_name>/.virtualenvs/<folder_name>/bin/postactivate",
    "python.unitTest.pyTestArgs": [
        "./<folder_name>/tests"
    ]
>}

If I run the tests manually from the VS Code terminal window (the small run button above test definition), they run properly and all of them pass. However, the test discovery fails with the test explorer.

Therefore I've deducted that the Test Explorer UI doesn't load the environmental variables used by VS Code from postactivate. I see that there is a similar issue that you fixed in the v0.2.4 but I am not sure why this is happening again. Can you please take a look at this? Thank you!

**Comment by kondratyev-nv** [comment] 2019-05-11 16:08
@mawan5512 Thank you for the issue! Indeed variables from `python.envFile` are loaded before test discovery and test execution. I tried to reproduce it with a small test (without Django) right now and had no issues. You can consult the log selecting `Python Test Adapter Log` in the Output section (same panel as Terminal). Please, let me know if you find anything useful there.

Also, I'm not sure if this is your complete workspace configuration, but testing should be enabled via properties `python.testing.unittestEnabled` or `python.testing.pyTestEnabled` depending on your test framework. Another thing that I noticed is that it looks like you have the old property for pytest arguments. Right now property `python.unitTest.pyTestArgs` has been renamed to `python.testing.pyTestArgs`. Do you have all the extensions up to date?

**Comment by mawan5512** [comment] 2019-05-13 19:12
Hi @kondratyev-nv Thank you for the response. 

Here is the log for the `Python Test Adaptor Log` in the output section. 

`% (desc, ENVIRONMENT_VARIABLE))
E   ImproperlyConfigured: Requested setting CONFIGURATION, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.`

I have the python.testing.pyTestEnabled set to True and other relevant settings in the user settings. The ones I posted before are from the folder settings. I was using the older version of the extension as the python microsoft extension had a bug that was found recently. I just updated the extension and tried the whole process again and I get the same error as above. I believe, for some reason the extension is not able to pick up the environment variable DJANGO_SETTINGS_MODULE from the postactivate file of the virutalenv. Is there is any other way to see whats wrong so that I can help you with more relevant logs. Thank you!

**Comment by kondratyev-nv** [comment] 2019-05-13 19:55
I have almost no experience with Django, but I will try to find an example and run it. If you have a simple example project on which your setup can be checked, it would be great.

Do you mind providing a sample from the `postactivate` file? It should be in a format described in https://code.visualstudio.com/docs/python/environments#_environment-variable-definitions-file.

Also, there should be some records on loading variables from the `envFile` in the log. Like `Loading environment variables file <path-to-your-env-file>`. Maybe you could notice something not right around there.

**Comment by akhilkumarco007** [comment] 2019-05-16 14:24
Hi @kondratyev-nv I work with @mawan5512. Apologies for the delayed response. It seems like the plugin detects the environment variables only if it inside the .env file in the root dir of the repo. The plugin is still looking for that file even after specifying it look for the file in path specified in the setting "python.envFile"(Confirmed this from the path it looks for the environment variables file in the python test adaptor log). We got it to be working by moving our environment variables to .env file from postactivate. 

Here is a link to a minimal django project that might help for your testing: https://github.com/syntarsus/minimal-django
To replicate the issue create a virtualenv outside the project repo and have the environment variables in the postactivate. To add settings to the django project, please edit the settings object in the minimal.py file of the django project to read from the environment variables list. Thank you!

**Comment by kondratyev-nv** [comment] 2019-05-20 10:46
@akhilkumarco007 Thank you for the additional information! I've tried to reproduce environment loading errors with various locations set in `python.envFile` and found a bug when `~` (home directory) was used in path. I will fix this soon. However, looking at your settings, it does not look like your issue is caused by the same bug (since you're using absolute path), does it?

**Comment by kondratyev-nv** [comment] 2019-05-22 09:18
@akhilkumarco007 @mawan5512 I've just published new version 0.3.6 with the fix regarding `~` (home directory) resolution. Please, update and let me know if the issue persists.

**Comment by akhilkumarco007** [comment] 2019-05-24 15:23
@kondratyev-nv thanks for the response. I tried it now and it seems to work. Thank you!

**Comment by kondratyev-nv** [comment] 2019-05-24 15:42
I will close this issue then. If you have any other questions, problems or feature requests, feel free to create a new issue!

**Closed by kondratyev-nv** 2019-05-24 15:42 UTC
