### ISSUE TITLE
Tests stuck in "loading" state.

### ISSUE THREAD

**Issue by valerierose** [kondratyev-nv/vscode-python-test-adapter#109] opened 2019-11-05 00:20 UTC
Since I updated VSCode last, I've had this issue which makes it easier to just run tests the old way, without the plugin.

Steps to reproduce:
- Run all tests with the "play" button at the top.
- Rerun an individual failing test with the "play" button for that test.

Expected behavior:
- The "X" icon turns to a loading indicator while the test is running.
- Then the icon turns to an "X" or a checkmark depending on the outcome.
- Other tests continue to update as they are run.

Actual behavior:
- The entire sidebar UI is stuck with the loading indicator on the first individual test that was rerun.
- Unable to run groups of tests -- the play buttons don't appear when hovering.

Here's what's in my "About Visual Studio Code":
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:00.827Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 15.6.0

**Comment by valerierose** [comment] 2019-11-05 00:36
It actually appears to be an issue with the underlying Test Explorer.

**Comment by kondratyev-nv** [comment] 2019-11-05 04:43
@valerierose Thank you for the issue! Unfortunately, I can not reproduce it. However, I have a couple of questions that might help:
1. What Python and test framework are you using? Also, do you use some additional plugins, maybe?
2. Do you have any other test adapters that you can reproduce the issue with after uninstalling this extension?
3. Can you provide a VSCode configuration from your settings.json file?

Any example project to reproduce the issue or even a screenshot also would be of help.

**Comment by valerierose** [comment] 2019-11-05 05:00
@kondratyev-nv Thanks for responding quickly. I think it's a problem with the underlying VS Code extension. Either way, to answer your questions:
1. I use pytest with the following plugins: sugar-0.9.2, picked-0.4.1, mock-1.10.4, cov-2.7.1, celery-4.3.0
2. I have Test Explorer UI installed. I still have the issue without the Python Test Adapter.
3. Here's my settings.json
```
{
  "editor.trimAutoWhitespace": false,
  "editor.useTabStops": true,
  "editor.tabSize": 4,
  "editor.wordWrapColumn": 119,
  "files.trimTrailingWhitespace": false,
  "python.linting.pylintEnabled": false,
  "python.linting.flake8Enabled": true,
  "python.linting.enabled": true,
  "python.pythonPath": "${workspaceFolder}/../bin/python",
  "python.testing.unittestEnabled": false,
  "python.testing.nosetestsEnabled": false,
  "python.venvPath": "${workspaceFolder}/../",
  "python.testing.pytestEnabled": true
}
```

**Comment by kondratyev-nv** [comment] 2019-11-05 05:31
@valerierose Thank you for the information. The reason why I asked the second question is that you might be having an issue with [Python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python). If you remove or disable Python Test Adapter, your Python tests won't be discovered and shown in Test Explorer UI at all.

Tests from Python extension and Test Explorer UI have a different look and located under different sections. For example, see the screenshot
![image](https://user-images.githubusercontent.com/4085884/68180602-6161d900-ffa5-11e9-9c27-5cf3741e23fd.png)
Tests from the Test Explorer UI are located under the "Test explorer" section. Of course, you won't see any without a test adapter (for example, this extension used to discover and run Python tests). However, tests from Python extension are located under the "Python" section and have different icons and structure.

**Comment by kondratyev-nv** [comment] 2019-11-05 05:48
Also, if you have Python Test Adapter installed, but don’t see any tests discovered in “Test Explorer” section, please consult “Python Test Adapter Log” in the Output section.

**Comment by valerierose** [comment] 2019-11-05 06:12
Thank you. It looks like an issue with the Python Extension, in that case.

**Comment by kondratyev-nv** [comment] 2019-11-05 06:35
Hope this helped you :) Anyway, you might consider using the Python Test Adapter, it is using the Python Extension settings, so no additional configuration is required. If no test would be discovered, feel free to create an issue here to investigate. And in case you want to report an issue to the Python Extension, here is their issues page - https://github.com/microsoft/vscode-python/issues.

**Comment by kondratyev-nv** [comment] 2019-11-11 12:29
I'm closing this issue since it looks like the problem is with Python Extension.

**Closed by kondratyev-nv** 2019-11-11 12:29 UTC
