### ISSUE TITLE
Can we use this extension with Django?

### ISSUE THREAD

**Issue by bblanchon** [kondratyev-nv/vscode-python-test-adapter#178] opened 2020-08-16 10:20 UTC
Hi,

I'm using the default test framework provided with Django.
To run the test suite, I launch the following command:

```
python manage.py test
```

When I try to run the tests from the Test Explorer, I get the following error:

> django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

This is the kind of error we get when running a `.py` file directly, out of the `manage.py`.
I looked in the settings, but I couldn't find a way to fix this.

Is there a way to use this extension with the Django Test framework?

Best regards,
Benoit

**Comment by kondratyev-nv** [comment] 2020-09-04 18:01
@bblanchon Thank you for the issue! I don't have a lot of experience with Django so an example with tests would be of help. I'll also try to find an example to reproduce the issue.
In the meantime, have you tried using pytest to run your tests? You can try running it from the command line
```
$python -m pytest
```
If it works you can setup the Test Explorer to use pytest to run tests.

**Comment by tuky** [comment] 2021-03-11 16:58
yes, it indeed works. you have to install `pytest` and `pytest-django`.

**Comment by bblanchon** [comment] 2021-03-12 13:37
Thanks for the advice, @tuky.
I didn't realize `pytest-django` would make the transition to pytest so smooth.

@kondratyev-nv, I think you should had a line about that in the README.
All the user needs to do is follow the [quick start of pytest-django](https://pytest-django.readthedocs.io/en/latest/tutorial.html).

**Comment by kondratyev-nv** [comment] 2021-07-05 08:50
Using `pytest-django` seems like a good solution, I've added this to the [README](https://github.com/kondratyev-nv/vscode-python-test-adapter#2-how-to-use-this-extesion-to-run-django-tests). I'm closing this issue as it seems to be resolved.

**Closed by kondratyev-nv** 2021-07-05 08:50 UTC
