### ISSUE TITLE
Not all tests get executed

### ISSUE THREAD

**Issue by SandroWissmann** [kondratyev-nv/vscode-python-test-adapter#181] opened 2020-08-23 16:29 UTC
I have the Issue that only one of my tests classes is executed:

![image](https://user-images.githubusercontent.com/42449992/90983374-fdc58e00-e56d-11ea-8a3c-c4b4a7b4dee4.png)

However the normal python test explorer catches them all:

![image](https://user-images.githubusercontent.com/42449992/90983388-1635a880-e56e-11ea-83b6-a1665403b69e.png)

My settings.json:

![image](https://user-images.githubusercontent.com/42449992/90983423-5137dc00-e56e-11ea-948c-5e953707e93b.png)

The structure of my project looks like this:

![image](https://user-images.githubusercontent.com/42449992/90983460-b1c71900-e56e-11ea-9c55-b8523474d4ac.png)

Full project structure can be seen [here](https://github.com/SandroWissmann/Bricks-Py)

So what is wrong here?

**Comment by kondratyev-nv** [comment] 2020-08-24 13:04
@SandroWissmann Thank you for the issue! Unfortunately, I can't reproduce it. I've cloned the repo you've provided, and I can discover and run tests without any issues.
<img width="648" alt="image" src="https://user-images.githubusercontent.com/4085884/91046799-bb5d8900-e621-11ea-83d3-213f017e2307.png">

Do you run all tests with the "Run all tests" button at the top of the Test Explorer panel? Also, what version of Python are you using? Have you tried looking at messages from the `Python Test Adapter Log` in the Output section?

**Comment by SandroWissmann** [comment] 2020-08-24 14:22
@kondratyev-nv 

Thanks for investigating.

I cklicked on the play all button. I see for like one second all the gray squares of the tests getting blue. Then only the test_physics.py test got green.


The pytest runner log:

`
2020-08-24T14:18:17.653Z info at 'Bricks_py' [pytest runner]: Reading configuration for workspace Bricks_py
2020-08-24T14:18:17.661Z info at 'Bricks_py' [pytest runner]: Environment variables file /home/sandro/Documents/Bricks_py/.env does not exist
2020-08-24T14:18:17.661Z info at 'Bricks_py' [pytest runner]: Discovering tests using python path '/home/sandro/Documents/Bricks_py/virtual/bin/python' in /home/sandro/Documents/Bricks_py
2020-08-24T14:18:17.662Z info at 'Bricks_py' [pytest runner]: Running pytest wrapper with arguments: --collect-only,tests
2020-08-24T14:18:35.713Z info at 'Bricks_py' [pytest runner]: Reading configuration for workspace Bricks_py
2020-08-24T14:18:35.714Z info at 'Bricks_py' [pytest runner]: Running tests using python path '/home/sandro/Documents/Bricks_py/virtual/bin/python' in /home/sandro/Documents/Bricks_py
2020-08-24T14:18:35.714Z info at 'Bricks_py' [pytest runner]: Environment variables file /home/sandro/Documents/Bricks_py/.env does not exist
2020-08-24T14:18:35.716Z info at 'Bricks_py' [pytest runner]: Running pytest wrapper with arguments: tests,--junitxml=/tmp/tmp-88212-36ieXPyEj3GC,--override-ini,junit_logging=all,--override-ini,junit_family=xunit1
2020-08-24T14:18:36.338Z info at 'Bricks_py' [pytest runner]: Test execution completed
2020-08-24T14:18:38.481Z info at 'Bricks_py' [pytest runner]: Reading configuration for workspace Bricks_py
2020-08-24T14:18:38.482Z info at 'Bricks_py' [pytest runner]: Running tests using python path '/home/sandro/Documents/Bricks_py/virtual/bin/python' in /home/sandro/Documents/Bricks_py
2020-08-24T14:18:38.483Z info at 'Bricks_py' [pytest runner]: Environment variables file /home/sandro/Documents/Bricks_py/.env does not exist
2020-08-24T14:18:38.484Z info at 'Bricks_py' [pytest runner]: Running pytest wrapper with arguments: tests,--junitxml=/tmp/tmp-88212-OLwdi5gxhkds,--override-ini,junit_logging=all,--override-ini,junit_family=xunit1
2020-08-24T14:18:39.101Z info at 'Bricks_py' [pytest runner]: Test execution completed
`

**Comment by kondratyev-nv** [comment] 2020-08-24 15:04
@SandroWissmann Thank you for clarification. Can you please tell me what version of Python you are using? While trying to reproduce the issue, I’ve installed pytest and numpy dependencies. Do you have any pytest plugins installed? Does running tests from the command line work for you? Can you show the output of something like
’’’
python -m pytest tests
’’’

**Comment by SandroWissmann** [comment] 2020-08-24 15:57
@kondratyev-nv 

You can see the python version below. I run it from a virtual environment.

VSCode Version 1.48.1

Installed Extensions:

> [sandro@sandro-pc ~]$ code --list-extensions | xargs -L 1 echo code --install-extension
code --install-extension DavidSchuldenfrei.gtest-adapter
code --install-extension hbenl.vscode-test-explorer
code --install-extension littlefoxteam.vscode-python-test-adapter
code --install-extension ms-python.python
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension notskm.clang-tidy
code --install-extension xaver.clang-format
code --install-extension yzhang.markdown-all-in-one




> (.venv) [sandro@sandro-pc Bricks_py]$ python -m pytest tests
================================================================================== test session starts ==================================================================================
platform linux -- Python 3.8.5, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/sandro/Documents/Bricks_py
plugins: cov-2.10.1
collected 304 items                                                                                                                                                                     

tests/game_objects/test_ball.py .....................                                                                                                                             [  6%]
tests/game_objects/test_brick.py ........                                                                                                                                         [  9%]
tests/game_objects/test_game_object.py ............                                                                                                                               [ 13%]
tests/game_objects/test_indestructible_brick.py ..                                                                                                                                [ 14%]
tests/game_objects/test_moveable_game_object.py ...                                                                                                                               [ 15%]
tests/game_objects/test_physics.py .............................................................................................................................................. [ 61%]
...............................                                                                                                                                                   [ 72%]
tests/game_objects/test_platform.py ....                                                                                                                                          [ 73%]
tests/game_objects/test_wall.py ..                                                                                                                                                [ 74%]
tests/types/test_angle.py ...............................................................................                                                                         [100%]

================================================================================== 304 passed in 0.45s ==================================================================================
(.venv) [sandro@sandro-pc Bricks_py]$

**Comment by SandroWissmann** [comment] 2020-08-24 16:46
Now it wotks in my repo aswell.

I changed were I create the virtual environment.

Before I createt it with 

`virtualenv virtual`

and referenced in settings (see above):

> "python.pythonPath": "virtual/bin/python"

Now I createtd it with

`virtualenv .venv`

and in settings (like you showed above):

> "python.pythonPath": ".venv/bin/python"

And now all gets detected:


![image](https://user-images.githubusercontent.com/42449992/91072577-04213c00-e63a-11ea-96fc-ea27423a6fb7.png)


kinda weired. Maybe you can try if changing the virtual env fodler to `virtual` causes the problem.

**Comment by kondratyev-nv** [comment] 2020-08-25 15:16
@SandroWissmann Glad to hear that you've got it fixed. I've tried to set up virtual env in a `virtual` folder, but still don't see any problems. I think we can close this issue, and if you have any other problems or suggestions, please, create a new issue.

**Comment by SandroWissmann** [comment] 2020-08-25 17:46
Yes I guess so. Looks like a rare problem to me. Maybe if somebody else has it as well we can reproduce it.

**Closed** 2020-08-26 14:40 UTC
